### ISSUE TITLE
Examples work, custom prompt for code base generation generate OpenAI Error 400

### ISSUE THREAD

**Issue by MorenoLabs** [samholt/L2MAC#3]
Super curious about L2MAC, have been testing the examples from quickstart but other basic requests e.g. 

>l2mac "create a eda app for csv file" (and other basic ones) throw ultimately after 2-3 steps the following error:

MainProcess| 2024-06-16 10:23:10,726,726 multiprocessing INFO [L2MAC][OpenAI API Request Error] <class 'openai.BadRequestError'> ('Error code: 400 - {\'error\': {\'message\': "An assistant message with \'tool_calls\' must be followed by tool messages responding to each \'tool_call_id\'. The following tool_call_ids did not have response messages: call_5NeB7YpcWw1zVdRgPjozrX0s", \'type\': \'invalid_request_error\', \'param\': \'messages.[5].role\', \'code\': None}}',) | num_retries: 0 / 10

it keeps retrying but same error. 

Any idea how to mitigate that? Researching this got no results. 

Thanks for your support!

**Comment by samholt** [comment]
Thank you for raising this. 

Yes, I believe I know how this is arising; it is coming from a missing tool response message. Are you able to share the complete log output?

I'll look into this and get back to you with a fix in the next few weeks at the latest.

**Comment by MorenoLabs** [comment]
Thx, I tried to reproduce it again with a clean install, now I keep getting differerent error `❯ l2mac "create a eda app for csv file"
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/morenolabs/coding/experiments/L2MAC_experiment/.venv/lib/python3.10/site-packages/l2mac/co │
│ re.py:76 in run_l2mac                                                                            │
│                                                                                                  │
│    73 │   log_path = generate_log_file_path(__file__, log_folder=config.setup.log_dir, config=   │
│    74 │   config.setup.log_path = log_path                                                       │
│    75 │   logger = create_logger_in_process(log_path)                                            │
│ ❱  76 │   rate_limiter = setup_chat_rate_limiter(config)                                         │
│    77 │   if config.wandb.track:                                                                 │
│    78 │   │   import wandb                                                                       │
│    79                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            config = L2MACConfig(                                                             │ │
│ │                     │   llm=LLMCoreConfig(                                                   │ │
│ │                     │   │   api_type=<ApiType.openai: 'openai'>,                             │ │
│ │                     │   │   model='wizardlm_wizardcoder-python-13b-v1.0',                    │ │
│ │                     │   │   base_url='http://localhost:1234/v1/models',                      │ │
│ │                     │   │   api_key='lm-studio',                                             │ │
│ │                     │   │   api_version=None                                                 │ │
│ │                     │   ),                                                                   │ │
│ │                     │   llm_settings=LLMSettingsConfig(                                      │ │
│ │                     │   │   temperature=0.01,                                                │ │
│ │                     │   │   top_p=1,                                                         │ │
│ │                     │   │   frequency_penalty=0,                                             │ │
│ │                     │   │   presence_penalty=0,                                              │ │
│ │                     │   │   stop='',                                                         │ │
│ │                     │   │   rate_limit_tier=<OpenAIRateLimitTier.tier3: 'tier3'>,            │ │
│ │                     │   │   rate_limit_requests_per_minute=3000,                             │ │
│ │                     │   │   api_retry_with_exponential_backoff__initial_delay=1,             │ │
│ │                     │   │   api_retry_with_exponential_backoff__exponential_base=2,          │ │
│ │                     │   │   api_retry_with_exponential_backoff__jitter=True,                 │ │
│ │                     │   │   api_retry_with_exponential_backoff__max_retries=10,              │ │
│ │                     │   │   api_stream=False                                                 │ │
│ │                     │   ),                                                                   │ │
│ │                     │   setup=SetupConfig(                                                   │ │
│ │                     │   │   debug_mode=True,                                                 │ │
│ │                     │   │   log_dir='logs',                                                  │ │
│ │                     │   │   enable_tests=True,                                               │ │
│ │                     │   │   log_path='logs/20240706-141730_log.txt',                         │ │
│ │                     │   │   seed=0                                                           │ │
│ │                     │   ),                                                                   │ │
│ │                     │   wandb=WandbConfig(project='l2mac', track=False)                      │ │
│ │                     )                                                                        │ │
│ │   debugging_level = <DebuggingLevel.info: 'info'>                                            │ │
│ │            domain = <Domain.codebase: 'codebase'>                                            │ │
│ │       init_config = False                                                                    │ │
│ │     l2mac_prompts = L2MACPrompts(                                                            │ │
│ │                     │   system='Objective: Write code for a large system design              │ │
│ │                     task.\nPlease note that the code '+1586,                                 │ │
│ │                     │   first_message='You will get instructions for code to write.\nFirst   │ │
│ │                     lay out the names of the core'+3340,                                     │ │
│ │                     │   reflect_on_prompt_program='Please reflect on the plan, and increase  │ │
│ │                     the number of generated steps to that o'+75,                             │ │
│ │                     │   test_writing_advice='All tests should always be interpretable and    │ │
│ │                     you should be able to clearly reaso'+378,                                │ │
│ │                     │   control_unit_execute_instruction='Objective: Execute sub task        │ │
│ │                     step:```{step}```.\\n\\n Note: Condition any new code '+631,             │ │
│ │                     │   control_unit_exhaust_context_window='You have exhausted your context │ │
│ │                     window. Reflect on your progress. Provide a shor'+135,                   │ │
│ │                     │   control_unit_instruction_complete_summarize_output='Please provide a │ │
│ │                     one or two sentence summary of the output of this step, which i'+121,    │ │
│ │                     │                                                                        │ │
│ │                     control_unit_instruction_erroring_fix_the_code='{error_message}\\n\\nRe… │ │
│ │                     and write the full complete corrected code to correct'+269,              │ │
│ │                     │   control_unit_cycle_message_to_check_if_instruction_complete='Has the │ │
│ │                     sub task step been completed of:```{step}```.\\n\\n If yes, call the     │ │
│ │                     funct'+422                                                               │ │
│ │                     )                                                                        │ │
│ │          log_path = 'logs/20240706-141730_log.txt'                                           │ │
│ │            logger = <Logger multiprocessing (INFO)>                                          │ │
│ │      project_name = None                                                                     │ │
│ │    prompt_program = None                                                                     │ │
│ │       prompt_task = 'create a eda app for csv file'                                          │ │
│ │ prompts_file_path = None                                                                     │ │
│ │         run_tests = False                                                                    │ │
│ │             steps = 10                                                                       │ │
│ │     tools_enabled = None                                                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/morenolabs/coding/experiments/L2MAC_experiment/.venv/lib/python3.10/site-packages/l2mac/ll │
│ m_providers/general.py:22 in setup_chat_rate_limiter                                             │
│                                                                                                  │
│    19                                                                                            │
│    20 def setup_chat_rate_limiter(config) -> ChatRateLimiter:                                    │
│    21 │   request_limit, token_limit = setup_chat_rate_limiter_internal(config)                  │
│ ❱  22 │   return ChatRateLimiter(request_limit=request_limit, token_limit=token_limit)           │
│    23                                                                                            │
│    24                                                                                            │
│    25 def remove_nulls(d):                                                                       │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ─────────────────────────────────────╮              │
│ │        config = L2MACConfig(                                                    │              │
│ │                 │   llm=LLMCoreConfig(                                          │              │
│ │                 │   │   api_type=<ApiType.openai: 'openai'>,                    │              │
│ │                 │   │   model='wizardlm_wizardcoder-python-13b-v1.0',           │              │
│ │                 │   │   base_url='http://localhost:1234/v1/models',             │              │
│ │                 │   │   api_key='lm-studio',                                    │              │
│ │                 │   │   api_version=None                                        │              │
│ │                 │   ),                                                          │              │
│ │                 │   llm_settings=LLMSettingsConfig(                             │              │
│ │                 │   │   temperature=0.01,                                       │              │
│ │                 │   │   top_p=1,                                                │              │
│ │                 │   │   frequency_penalty=0,                                    │              │
│ │                 │   │   presence_penalty=0,                                     │              │
│ │                 │   │   stop='',                                                │              │
│ │                 │   │   rate_limit_tier=<OpenAIRateLimitTier.tier3: 'tier3'>,   │              │
│ │                 │   │   rate_limit_requests_per_minute=3000,                    │              │
│ │                 │   │   api_retry_with_exponential_backoff__initial_delay=1,    │              │
│ │                 │   │   api_retry_with_exponential_backoff__exponential_base=2, │              │
│ │                 │   │   api_retry_with_exponential_backoff__jitter=True,        │              │
│ │                 │   │   api_retry_with_exponential_backoff__max_retries=10,     │              │
│ │                 │   │   api_stream=False                                        │              │
│ │                 │   ),                                                          │              │
│ │                 │   setup=SetupConfig(                                          │              │
│ │                 │   │   debug_mode=True,                                        │              │
│ │                 │   │   log_dir='logs',                                         │              │
│ │                 │   │   enable_tests=True,                                      │              │
│ │                 │   │   log_path='logs/20240706-141730_log.txt',                │              │
│ │                 │   │   seed=0                                                  │              │
│ │                 │   ),                                                          │              │
│ │                 │   wandb=WandbConfig(project='l2mac', track=False)             │              │
│ │                 )                                                               │              │
│ │ request_limit = 100                                                             │              │
│ │   token_limit = None                                                            │              │
│ ╰─────────────────────────────────────────────────────────────────────────────────╯              │
│                                                                                                  │
│ /home/morenolabs/coding/experiments/L2MAC_experiment/.venv/lib/python3.10/site-packages/l2mac/ll │
│ m_providers/rate_limiter.py:58 in __init__                                                       │
│                                                                                                  │
│   55                                                                                             │
│   56 class ChatRateLimiter(RateLimiter):                                                         │
│   57 │   def __init__(self, request_limit=3500, token_limit=90000):                              │
│ ❱ 58 │   │   super().__init__(                                                                   │
│   59 │   │   │   request_limit_per_minute=request_limit,                                         │
│   60 │   │   │   token_limit_per_minute=token_limit,                                             │
│   61 │   │   │   token_counter=num_tokens_consumed_by_chat_request,                              │
│                                                                                                  │
│ ╭────────────────────────────────────────── locals ───────────────────────────────────────────╮  │
│ │ request_limit = 100                                                                         │  │
│ │          self = <l2mac.llm_providers.rate_limiter.ChatRateLimiter object at 0x7f97d52045e0> │  │
│ │   token_limit = None                                                                        │  │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────╯  │
│                                                                                                  │
│ /home/morenolabs/coding/experiments/L2MAC_experiment/.venv/lib/python3.10/site-packages/l2mac/ll │
│ m_providers/rate_limiter.py:44 in __init__                                                       │
│                                                                                                  │
│   41 │   │                                                                                       │
│   42 │   │   # Buckets                                                                           │
│   43 │   │   self._request_bucket = TokenBucket(self.request_limit / 60.0, self.request_limit    │
│ ❱ 44 │   │   self._token_bucket = TokenBucket(self.token_limit / 60.0, self.token_limit)         │
│   45 │                                                                                           │
│   46 │   def consume(self, **kwargs):                                                            │
│   47 │   │   num_tokens = self.token_counter(**kwargs)                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ request_limit_per_minute = 100                                                               │ │
│ │                     self = <l2mac.llm_providers.rate_limiter.ChatRateLimiter object at       │ │
│ │                            0x7f97d52045e0>                                                   │ │
│ │            token_counter = <function num_tokens_consumed_by_chat_request at 0x7f97d5f969e0>  │ │
│ │   token_limit_per_minute = None                                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
MainProcess| 2024-07-06 14:17:30,317,317 multiprocessing INFO process shutting down`

**Comment by MorenoLabs** [comment]
This is all I am getting 

`MainProcess| 2024-07-06 19:34:33,878,878 multiprocessing INFO [User] Has the sub task step been completed of:```In the 'app.py' file, integrate the 'eda.py' and 'data_store.py' functionalities. Update the upload route to save the uploaded CSV file to the mock database and call the 'perform_eda' function. Update the route to display the EDA results to retrieve the results from the mock database. Write tests to ensure the integration works correctly and the EDA results are displayed as expected.```.\n\n If yes, call the function `sub_task_step_complete`, otherwise reflect and correct the full code to complete the task. Note: Condition any new code files on the existing code files: ['app.py', 'requirements.txt', 'eda/__init__.py', 'test_project_structure.py', 'test_app.py', 'eda/eda.py', 'test_eda.py', 'eda/data_store.py', 'test_data_store.py']. Fully implement these features in the code, no placeholders.\n Respond now only with a function call of one of the following functions provided: `sub_task_step_complete`, `view_files`, `run_python_file`, `pytest_files`, `write_files`, `delete_files`, and if you want to output code only use the `write_files` function to output code.`

**Comment by MorenoLabs** [comment]
this is all I am getting, just keeps retrying:

MainProcess| 2024-07-06 19:34:34,507,507 multiprocessing INFO [L2MAC][OpenAI API Request Error] <class 'openai.BadRequestError'> ('Error code: 400 - {\'error\': {\'message\': "An assistant message with \'tool_calls\' must be followed by tool messages responding to each \'tool_call_id\'. The following tool_call_ids did not have response messages: call_Ma2hfBLbX9wA8lDM3ggq1TfQ", \'type\': \'invalid_request_error\', \'param\': \'messages.[5].role\', \'code\': None}}',) | num_retries: 0 / 10
MainProcess| 2024-07-06 19:34:34,507,507 multiprocessing INFO [L2MAC][OpenAI API Request Error] <class 'openai.BadRequestError'> ('Error code: 400 - {\'error\': {\'message\': "An assistant message with \'tool_calls\' must be followed by tool messages responding to each \'tool_call_id\'. The following tool_call_ids did not have response messages: call_Ma2hfBLbX9wA8lDM3ggq1TfQ", \'type\': \'invalid_request_error\', \'param\': \'messages.[5].role\', \'code\': None}}',) | num_retries: 1 / 10 | Now sleeping for 3.6888437030500962 seconds

**Comment by MorenoLabs** [comment]
here is the log output file
[20240706-193334_log.txt](https://github.com/user-attachments/files/16115820/20240706-193334_log.txt)

**Comment by ballidev** [comment]
have had a similar problem using openAI gpt-4o

tried again with turbo and it has worked

**Comment by samholt** [comment]
Hi @MorenoLabs @ballidev,

Thank you for your patience. I was able to replicate this bug, and I have now pushed a fix that resolves this bug. Thank you for reporting.

I have also improved the overall codebase to make L2MAC more stable,

Feel free to let me know if you have any further issues using it,

Best,
Sam
